# render.yaml (must live at the repo root)

###############################################################################
# FlipApp • Render Blueprint – frontend + backend + Redis (free tier)         #
###############################################################################

services:
  # ───────── BACKEND (FastAPI) ─────────
  - name: flip-backend
    type: web
    env: python
    plan: free
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: REDIS_URL
        fromDatabase:
          name: flip-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: LOG_PATH
        value: "/render/logs"
      - key: LOG_MAX_MB
        value: "10"
      - key: LINK_TTL_SEC
        value: "7200"
      - key: OPENAI_API_KEY
        sync: false       # mark as secret in Dashboard, not here
    autoDeploy: true
    healthCheckPath: /healthz

  # ───────── FRONTEND (Next.js) ─────────
  - name: flip-frontend
    type: web
    env: node
    plan: free
    rootDir: frontend
    buildCommand: |
      npm ci
      npm run build
    startCommand: |
      npm run start -p $PORT
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        fromService:
          name: flip-backend
          type: web
          envVarKey: RENDER_INTERNAL_HOST   # will resolve to e.g. 10.0.0.123:8000
      - key: NEXT_PUBLIC_TENANT_ID
        value: "voulezvous"
      - key: NEXT_PUBLIC_USER_ID
        value: "danvoulez"
    pullRequestPreviewsEnabled: false
    autoDeploy: true

databases:
  # ───────── REDIS (gerenciado) ─────────
  - name: flip-redis
    type: redis
    plan: free
