# render.yaml (repo root)

services:
  # ───────── BACKEND (Flask + SocketIO) ─────────
  - name: flip-backend
    type: web
    env: python
    plan: free
    rootDir: backend
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn -k eventlet -w 1 app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: REDIS_URL
        fromService:
          name: flip-redis
          type: redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: LOG_PATH
        value: "/render/logs"
      - key: LOG_MAX_MB
        value: "10"
      - key: LINK_TTL_SEC
        value: "7200"
      - key: OPENAI_API_KEY
        sync: false
    autoDeploy: true
    healthCheckPath: /healthz

  # ───────── FRONTEND (Next.js) ─────────
  - name: flip-frontend
    type: web
    env: node
    plan: free
    rootDir: frontend
    buildCommand: |
      npm ci
      npm run build
    startCommand: |
      npm run start -p $PORT
    envVars:
      - key: NEXT_PUBLIC_API_BASE
        fromService:
          name: flip-backend
          type: web
          property: hostport
      - key: NEXT_PUBLIC_TENANT_ID
        value: "voulezvous"
      - key: NEXT_PUBLIC_USER_ID
        value: "danvoulez"
    pullRequestPreviewsEnabled: false
    autoDeploy: true

  # ───────── REDIS (gerenciado) ─────────
  - name: flip-redis
    type: redis
    plan: free
    ipAllowList: []
